### ISSUE TITLE
Image sur la page d'accueil qui a disparu

### ISSUE THREAD

**Issue by NothRen** [edenfoxwind/maquettesHTML#10]
L'image sur la page d'accueil n'est plus là : 

![image](https://user-images.githubusercontent.com/56638442/116545876-3eda2300-a8f1-11eb-9c5d-77e0b026c49d.png)

**Comment by NicolasEden** [comment]
Problème corrigé avec le commit 78192dff11293a6976887977520d00e3bfc372b3
